### ISSUE TITLE
Edit in Programming View broken

### ISSUE THREAD

**Issue by dgruntz** [explore-it-org/robby-app#11]
If on the program view a speed field is focused, then the keyboard opens (as shown on the picture below).

However, if the text field on the last, second last or third last row is focused, the keyboard opens and closes immediately. This happens with programs which have 8 or more lines. On programs with 6 lines this happens if a text field on the last line is focused, and on programs with 7 lines this happens for the text fields on the last and the second last line.

Once the keyboard is open, then all fields can be focused and edited.

This problem does not show up if the program is used in landscape mode.

![Screenshot_20190411-185850](https://user-images.githubusercontent.com/1516800/55976551-e8a7d200-5c8c-11e9-9825-eca8bdb14474.png)

**Comment by dgruntz** [comment]
In version 0.5.5 and 0.5.6 this was not yet a problem.

**Comment by MichaelStotzer** [comment]
I believe this issue can be closed
