### ISSUE TITLE
Settings.interval field

### ISSUE THREAD

**Issue by dgruntz** [explore-it-org/robby-app#132]
Frage: Was soll im Settings-Dialog im Interval-Feld dargestellt werden wenn das Handy nicht mit einem Roboter verbunden ist? Aktuell ist das Feld nicht editierbar (das ist gut), aber es wird einfach der Wert des letzten Roboters dargestellt. Könnte man das Feld auch leer lassen? Oder Wäre es eine Variante, dieses Feld gerade ganz auszublenden, also nur anzuzeigen wenn der Roboter verbunden ist?

**Comment by faqnet** [comment]
Ausblenden finde ich nicht schlecht

**Comment by dgruntz** [comment]
Ok, dann machen wir das doch so!
