### ISSUE TITLE
Initial Language

### ISSUE THREAD

**Issue by dgruntz** [explore-it-org/robby-app#139]
Kann die Spracheinstellung auf dem Handy mit folgender Library ausgelesen werden?

    https://github.com/react-native-community/react-native-localize

Sie schreiben da was bezüglich 0.60.0+ und Linking. Wir benötigen nur die Methode
`findBestAvailableLanguage`.

> Returns the best language tag possible and its reading direction (warning it respects the user preferred languages list order, see explanations). Useful to pick the best translation available.

Method type

	type findBestAvailableLanguage = (
	  languageTags: Array<string>,
	) => { languageTag: string; isRTL: boolean } | void;

Usage example

	console.log(RNLocalize.findBestAvailableLanguage(["en-US", "en", "fr"]));
	// -> { languageTag: "en-US", isRTL: false }

**Comment by dgruntz** [comment]
Auf [Stackoverflow](https://stackoverflow.com/questions/33468746/whats-the-best-way-to-get-device-locale-in-react-native-ios) habe ich folgende Lösung gefunden:

	import { NativeModules } from 'react-native'

	// iOS:
	const locale = NativeModules.SettingsManager.settings.AppleLocale // "fr_FR"

	// Android:
	const locale = NativeModules.I18nManager.localeIdentifier // "fr_FR"

Auf meinem Android kommt `en-US` raus. Und die Unterscheidung ob iOS oder Android könnte man mit einem if auf `Platform.OS`  machen.

**Comment by faqnet** [comment]
RNLocalize hatten wir früher und das hatte massive Probleme mit 0.60+ 

Wi hatten sie dann durch das NativeModul ersetzt und das ging im ganzen Redux refactoring  verloren

**Comment by dgruntz** [comment]
Ah, wusste ich nicht dass wir das mit `NativeModul` ersetzt haben.
@JonasDev99, dann könntest Du die Initialeinstellung mit `NativeModul` realisieren, dann müssen wir weder der Deutschscheiz noch der welschen Schweiz einen Vorzug geben.
