### ISSUE TITLE
wrong font is used

### ISSUE THREAD

**Issue by faqnet** [explore-it-org/robby-app#144]
app uses default font which is diffrent depending on the os. Global font should be added

**Comment by faqnet** [comment]
Wir müssen uns noch für einen Font entscheiden @dgruntz

**Comment by dgruntz** [comment]
Was gibt es alles für Fonts aus denen wir wählen können? Ist das dann ein Font für Android und iOS?
Könnte man dazu allenfalls Uli fragen?

**Comment by faqnet** [comment]
im Grunde aus jeglichen Fonts, die Applikation kann leicht um einen Font erweitert werden.  Gerne den selben Font für iOS und Android, zurzeit nimmt iOS den default Font von Apple und Android den von Google. Uli wird wahrscheinlich die bessere Wahl treffen als wir könnten.

**Comment by dgruntz** [comment]
Der Font wird dann einfach in die App gepackt?

Aber frag doch Uli.

**Comment by faqnet** [comment]
jap

**Comment by faqnet** [comment]
https://indestructibletype.com/Jost.html
