### ISSUE TITLE
Multiple listeners after a reconnect to the robot

### ISSUE THREAD

**Issue by MichaelStotzer** [explore-it-org/robby-app#16]
If the robot gets disconnected and instructions are loaded from the robot to the smartphone speed entries will get doubled. This error can be reproduced by turning the robot off and on again, or by simply disconnecting and then reconnecting through the application.

**Comment by dgruntz** [comment]
Method `device.monitorCharacteristicForService` (which is used in class [BleService.js](https://github.com/explore-it-org/robby-app/blob/master/communication/BleService.js) at line 92 returns a subscription object. This return value is ignored in our application. Probably this object should be stored and should be used to cancel a running subscritpion. This subscription provides a `remove()` method which could be used to remove the old subscription.

Documentation: https://polidea.github.io/react-native-ble-plx/#blemanagermonitorcharacteristicfordevice

**Comment by MichaelStotzer** [comment]
If the robot is turned off and we then click on disconnect the error "BleError: Device 00:07:80:72:AD:CF is not connected" occurs. So a clean disconnect can't be made and thus the listeners not be deregistered.

**Comment by dgruntz** [comment]
Fixed with pull request #18.
