### ISSUE TITLE
Last row must not be deleted

### ISSUE THREAD

**Issue by dgruntz** [explore-it-org/robby-app#17]
Currently it is possible to remove *all* lines from the programming view. New lines can still be added in this situation, but if an empty program is downloaded then the downloading process will not terminate. Method `upload` sends the following commands to the robot:

    F
    D0
    I1
    E
    ,,,,

The robot however does not allow that the duration `D` is set to 0, so it will internally assign the value 1. As a consequence, the robot is awaiting at least 1 line which is not sent by the above program, so the will wait indefinitely for a confirmation.

### Task:
It should not be possible to remove the last row, i.e. a program should always contain at least one row.

An alternative solution would be to disable the download button if the program contains less than one row. I do not know what is easier to implement. At least, empty programs should not be storable. In some situations it might be simpler to delete all lines and create new ones than to change them, but the new lines have to be edited anyway, so it propose to prevent the definition of empty programs.

![image](https://user-images.githubusercontent.com/1516800/56127742-22732400-5f7e-11e9-8b8e-1bef1df3f531.png)

**Comment by dgruntz** [comment]
Idea: The delete button should be disabled (similar to the down/up buttons if the selected row is the last/first one).

**Comment by MichaelStotzer** [comment]
The disabled delete button idea was implemented in the last pull request and is ready for review.

**Comment by dgruntz** [comment]
Fixed with merge #19.
