### ISSUE TITLE
Settings Dialog

### ISSUE THREAD

**Issue by dgruntz** [explore-it-org/robby-app#174]
Der Settings-Dialog ist aktuell kaputt und ich vermute, dass das daran liegt dass wir den aktuellen Stand des Branches von Jonas gemerged haben, d.h. dass wir WIP integriert haben.

Trotzdem erlaube ich mir den aktuellen Stand als Issue zu erfassen:

1. Das Interval - Feld fehlt (habe gesehen dass eine Methode `renderIntervalField` definiert wurde, aber diese wird noch nirgends verwendet.
2. Die Zahlen die in das Duration/Dauer-Feld geschrieben werden werden nicht übernommen (d.h. wenn ich den Settings-Dialog aufmache ist dieses Feld immer leer)
3. Es findet keine Bereichsüberprüfung statt.

![image](https://user-images.githubusercontent.com/1516800/70851362-7bd87d80-1e94-11ea-9c38-0a16fe103cc0.png)

**Comment by JonasDev99** [comment]
Muss der Bereich überprüft werden?
