### ISSUE TITLE
i18n: Unknown

### ISSUE THREAD

**Issue by dgruntz** [explore-it-org/robby-app#177]
In der Datei BleReducer.js wird das Device wie folgt initialisiert:

    device: {
        name: "Unknown",
        version: 1,
        isRecording: false,
        isRunning: false,
        isUploading: false,
        isDownloading: false,
        isGoing: false,
    },

Sollte der Name `Unknown` nicht internationalisiert werden? Man könnte auch argumentieren dass `Unknown` ein sinnvoller _Device-Name_ in allen Sprachen ist.

Es gibt aber noch den Eintrag im Ressourcenfile `Programming.bleDefaultDeviceName` und dieser wird aktuell nicht (bzw. nicht mehr) verwendet.

**Comment by faqnet** [comment]
Jonas hat den entfernt weil die i18n Ersetztung nicht funktioniert hat

**Comment by dgruntz** [comment]
Das Mapping in der Ressource war entfernt, und als Folge davon habe ich einen nicht übersetzten Ressource-String in der App gesehen, d.h. es hat also doch mal funktioniert.

**Comment by JonasDev99** [comment]
Es hat nur halbwegs funktioniert. Der Text wurde zwar vom i18n resource file geladen, veränderte sich jedoch nicht beim Wechseln der Sprache.

**Comment by dgruntz** [comment]
Kann es sein dass dieser Wert dann in einem Default gespeichert worden ist? Im BleReducer steht aktuell

    device: {
        name: "Unknown",
        version: 1,
        isRecording: false,
        isRunning: false,
        isUploading: false,
        isDownloading: false,
        isGoing: false,
    },

d.h. sobald dieser Code ausgeführt wird wird IMMER "Unknown" ausgegeben (unabhängig von jedem Eintrag in den Sprach-Resource-Files).

Aber ich denke wir haben vorerst wichtigeres zu tun, bzw. ich weiss nicht ob "Unknown" überhaupt hilfreich ist, denn eigentlich ist man ja nicht mit "unknwon" verbunden sondern gar nicht.
