### ISSUE TITLE
Playstore / Appstore

### ISSUE THREAD

**Issue by dgruntz** [explore-it-org/robby-app#181]
Im Playstore / Appstore müssen die Bilder aktualisiert werden. Aus meiner Sicht genügen 4 BIlder (in dieser Reihenfolge):
- Sequenzprogramm
- Blockprogramm
- Übersicht
- Settings
und allenfalls noch ein Bild (Foto) des Roboters.

**Comment by dgruntz** [comment]
Das dritte Bild (Übersicht) ist nicht mehr aktuell, d.h. die Icons die den Typ der Applikation angeben sind auf diesem Bild noch nicht vorhanden. Und wenn wir schon dabei sind: Auf der Settings-Seite stimmt die Versionsnummer nicht mehr (im Bild das ich auf dem Play-Store sehe).

**Comment by JonasDev99** [comment]
#294 ;)

**Comment by dgruntz** [comment]
alles klar. Habe mich von hinten durch die Emails gearbeitet.
