### ISSUE TITLE
TextInput value not visible 

### ISSUE THREAD

**Issue by dvogelin** [explore-it-org/robby-app#194]
Bei meinem I-Phone 6 sind die Ziffern in den Motorwerte-Eingabefeldern nicht erkennbar (ev. weiss), obwohl der Farbbalken angezeigt wird.

**Comment by faqnet** [comment]
![EC826E31-4CE5-4528-A5D4-50882453E9EE](https://user-images.githubusercontent.com/20967248/71057727-fd166580-215d-11ea-825a-7c32ddf95565.png)

![821C0E8E-5B6E-4A32-9BD0-404D868E333F](https://user-images.githubusercontent.com/20967248/71057817-38b12f80-215e-11ea-869c-ae16590821ea.png)

**Comment by faqnet** [comment]
#209
