### ISSUE TITLE
Anpassung Sprache

### ISSUE THREAD

**Issue by dgruntz** [explore-it-org/robby-app#197]
Wenn die Sprache gewechselt wird, dann wird die Anzeige im Block-Programm nicht angepasst. Im folgenden Screen ist die Sprache auf Englisch umgestellt worden (sieht man an "Device" im Titelbalken) aber im leeren Block steht weiterhin "Wählen Sie ein Programm...".

![image](https://user-images.githubusercontent.com/1516800/71065315-550a9780-2171-11ea-9f90-62bba57b0d9a.png)

**Comment by faqnet** [comment]
sollen wir das fixen oder ersetzt wir den text ..., im allgemeinen ist es relativ eifach wenn wir das array wieder neu abfüllen. Wenn der Text aber sowieso überall ... dann braucht es das nicht

**Comment by dgruntz** [comment]
Gute Frage. Vielleicht konnt da mal noch ein anderer Vorschlag für diesen Text, denn `...` finde ich nicht sehr verständlich. Wenn es bei `...` bleibt, dann können wir das auch aus den Ressourcen rausnehmen und fest im Code einbauen, denn jetzt ist es über die Ressourcefiles sprachabhängig einstellbabr, aber es wird nicht sofort angepasst, also ein Bug.

Wenn wir diesen Bug nun beheben, und der Eintrag bleibt bei `...` dann ist das auch doof.


Frage: Ist das jetzt eine Änderung die man leicht machen könnte, da wir mit Redux arbeiten?

**Comment by faqnet** [comment]
hab es angepasst, list wird jetzt neu gerendert beim Sprachwechsel
