### ISSUE TITLE
Übersetztung

### ISSUE THREAD

**Issue by faqnet** [explore-it-org/robby-app#201]
Wir haben R und L für Left und Right oder Links und Rechts für Italienisch stimmt das aber nicht mehr.

**Comment by faqnet** [comment]
![image](https://user-images.githubusercontent.com/20967248/71070262-b2efad00-217a-11ea-8488-eb74f48bdae9.png)
Einige Texte sind im Italienisch "zu Lang"

**Comment by dgruntz** [comment]
Beim Französischen ist links gauche (G) und rechts droite (D).
Wir müssen das über Ressourcen auflösen.

**Comment by dgruntz** [comment]
L/R fixed with commit #208
