### ISSUE TITLE
Programmnamen zu klein

### ISSUE THREAD

**Issue by dvogelin** [explore-it-org/robby-app#205]
![B88908BE-2D70-49D4-99A6-E5069F06D645](https://user-images.githubusercontent.com/50146134/71093071-be59cd00-21a8-11ea-8a78-0263fb73d70e.png)
Die Icons wirken zu wichtig gegenüber der Schrift.
Ev. Icons kleiner und ev.  auch grau, wie die Seiten-Ueberschrift-Icons.

**Comment by faqnet** [comment]
Fixed in Release 2.0.4
