### ISSUE TITLE
Darstellungsprobleme

### ISSUE THREAD

**Issue by dvogelin** [explore-it-org/robby-app#207]
![670E74EF-B684-47B6-965D-549E6420BFEE](https://user-images.githubusercontent.com/50146134/71097694-aede8200-21b0-11ea-8219-b33f96997191.png)
![30AF365E-2604-459A-9D3A-F563CA97140D](https://user-images.githubusercontent.com/50146134/71097695-aede8200-21b0-11ea-92ff-f4c7f022e321.png)
 Die Texte „Geschwindigkeit“ und im Italienischen der Titel werden nicht vollständig gezeigt. Der +  Button ist nicht vollständig.

**Comment by faqnet** [comment]
Kannst du mir die iOS Version und die iPhone Version durchgeben? Ich denke das wir extra für diese diese älteren Geräte jegliches css anpassen müssen.

**Comment by dgruntz** [comment]
@dvogelin, man sieht beim Namensfeld dass da `Programmname` steht.

@faqnet kann man diesen Hintergrundtext (zimindest auf iOS) etwas dünkler machen?

**Comment by dvogelin** [comment]
Hoi Robin
Ich habe iPhone6 und IOS13.3
Gruss
Daniel

**Comment by faqnet** [comment]
@dgruntz Bei meinen Geräten ist es deutlich dünkler. 
@dvogelin Was für Optionen hast du alles aktiviert? es sieht so als wäre alles gezoomed.

**Comment by faqnet** [comment]
@dgruntz das Darkthem färbt alles #209 das ist auch der Bug weshalb die Inputfelder "leer" sind. Bei mir trat es nur manchmal auf weil ich das Darktheme von 21.00 - 6.00 aktiviert habe.

**Comment by dgruntz** [comment]
:+1:  Super, jetzt bin ich beruhigt! 
Danel hat mir am Telefon gesagt, dass er Darktheme aktiviert habe. Das ist es!
Zum Glück arbeiten wir Informatiker auch machnchmal nachts ....
