### ISSUE TITLE
Programmabsturz bei langen Programmen

### ISSUE THREAD

**Issue by dgruntz** [explore-it-org/robby-app#210]
Folgendes Szenario:

1) Settings => Intervall auf 50 setzen
2) Settings => Dauer auf 5 setzen
3) Programm aufzeichnen (Record)
4) Programm runterladen (=> Programm mit 250 Zeilen, dauert etwas)
5) Speichern des Programms unter einem Namen (z.B. LONG).
6) Erzugen eines neuen Programms (+) auf Programmierseite
7) Wechsel auf Listing und Laden des Programms LONG

Absturz.
In dieser Situation ist es mir auch passiert dass die Applikation geade nach dem Start erneut abgestürzt ist. 
Bugreports müssten auf dem  [Android-Portal](https://play.google.com/apps/publish/?account=5912664164285981355#AndroidMetricsErrorsPlace:p=org.exploreit.robotics&appid=4976362727805583574&appVersion=1576591854&showHidden=true&installSource=INSTALLED_FROM_ANYWHERE&clusterName=apps/org.exploreit.robotics/clusters/04b0b591&detailsAppVersion=1576591854&detailsSpan=7&detailsInstallSource=INSTALLED_FROM_ANYWHERE) sein. 
Dort wird eine NPE angezeigt.

**Comment by dgruntz** [comment]
Vielleicht hilft dieses Bild noch weiter: Wenn ich dieses lange Programm lade, dann wechselt die View nicht mehr, d.h. der Balken oben zeigt an als sei ich immer noch auf dem dritten Tab, obwohl ja das Programm dargestellt wird.

![image](https://user-images.githubusercontent.com/1516800/71107021-9f673500-21c0-11ea-917a-cb1a9e8defec.png)

**Comment by faqnet** [comment]
https://github.com/facebook/react-native/issues/17530#issuecomment-534105719

**Comment by JonasDev99** [comment]
Tritt bei mir nicht mehr auf (Protokoll V10)

**Comment by JonasDev99** [comment]
Kann geschlossen werden, falls dies ein altes Problem ist.

**Comment by dgruntz** [comment]
Ich konnte dieses Problem (so wie oben beschrieben) auch auf meinem Gerät nicht mehr reproduzieren, daher kann dieses issue geschlossen werden. Ich habe aber mit #301 ein neues Issue erfasst mit einer ähnlichen Ausgangslage.
