### ISSUE TITLE
Plusbutton angeschnitten

### ISSUE THREAD

**Issue by dvogelin** [explore-it-org/robby-app#211]
Auf meinem IPhone ist der Plusbutton angeschnitten
Dies auch wenn die anderen blauen Buttons dazu kommen

![IMG_8402](https://user-images.githubusercontent.com/50146134/71105757-60d07b00-21be-11ea-8944-dfad848b3283.png)

**Comment by faqnet** [comment]
du hast bei den iphone einstellungen eine grosse Schrift aktiviert und den Zoommodus. ich schau mir das an, wenn du gerne ohne diese Probleme testen willst dann kannst du das in den iPhone settings abschalten
![6BA9E717-211C-4769-B05C-C0320A64AE48](https://user-images.githubusercontent.com/20967248/71107943-5f08b680-21c2-11ea-86e3-2b71258e7049.png)
![24BA0881-BE81-43D6-8BFC-49073BB3E668](https://user-images.githubusercontent.com/20967248/71107944-5f08b680-21c2-11ea-9237-0e05206bae7f.png)
