### ISSUE TITLE
Settings Screen

### ISSUE THREAD

**Issue by dgruntz** [explore-it-org/robby-app#214]
Auf dem Settings-Screen sollte noch die Versionsnummer erscheinen, und das Logo sollte ein Link auf explore-it.org sein, oder anstelle des Logos nur ein Link (der als solcher erkennbar ist).

![image](https://user-images.githubusercontent.com/1516800/71118153-cc731200-21d7-11ea-9b71-689c750274f2.png)

**Comment by faqnet** [comment]
Bitte Vorschläge für die Darstellung Link/Logo gefällt mir nicht, zurzeit ist logo und "Link" ein link auf explore-it.org
![image](https://user-images.githubusercontent.com/20967248/71172523-c2e1bc80-2260-11ea-815f-2462627ebe07.png)

**Comment by dgruntz** [comment]
Ich finde auch dass das Logo nicht gut rein passt. Ich hätte schlicht geschrieben:

Version 2.0.2
(c) 2020, www.explore-it.org

Oder, um im Layout der Settings-Seite zu bleiben (linksbündig):

### Information: ###
Version 2.0.2
(c) 2020, www.explore-it.org

**Comment by dgruntz** [comment]
@dvogelin, was ist Deine Meinung?

**Comment by faqnet** [comment]
![image](https://user-images.githubusercontent.com/20967248/71182129-d3e8f880-2275-11ea-9b2b-bf8bcdaf0076.png)

**Comment by faqnet** [comment]
> Ich finde auch dass das Logo nicht gut rein passt. Ich hätte schlicht geschrieben:
> 
> Version 2.0.2
> (c) 2020, [www.explore-it.org](http://www.explore-it.org)
> 
> Oder, um im Layout der Settings-Seite zu bleiben (linksbündig):
> 
> ### Information:
> Version 2.0.2
> (c) 2020, [www.explore-it.org](http://www.explore-it.org)

sieht nicht so gut aus weil nicht alles auf einer Linie ist
