### ISSUE TITLE
Maximale Programmlänge

### ISSUE THREAD

**Issue by dgruntz** [explore-it-org/robby-app#216]
Der Roboter kann nur eine endliche Anzahl Progammschritte entgegennehmen, aber diese Schranke wird aktuell nicht geprüft. Eigentlich müsste verhindert werden dass man Programme erzeugen (bzw. speichern) kann die zu lange sind.

Ich muss bei Peter Steigmeier nachfragen, was die maximale Programmlänge ist.

**Comment by dgruntz** [comment]
Antwort von Peter Steigmeier:

    Ich begrenze das "d max" auf  0x1FFF  = 8191
    = ROB_MAX_FLASH; das sind also 4095 Paar-Einträge.

**Comment by faqnet** [comment]
Für Stepprogram implementiert

Wie sollen wir das bei den Blocks handlen?
Einerseits kann es zu gross werden durch mehr Elemente anderseits auch durch änderen des Refernzierten Blocks oder wenn ein andere Faktor gewählt wird

**Comment by dgruntz** [comment]
Man könnte es gleich machen wie bei den Stepprogrammen, d.h. vor dem Speichern prüfen der Länge (die ist dann definiert) und das Speichern verweigern wenn zu gross.

Aber Du hast recht, wenn nachträglich Subprogramme geändertw werden, dann werden die Programme zu gross. Das kann man eigentlich nur noch beim Download abfangen, d.h. man müsste zusätzlich beim Download prüfen, ob das Programm zu gross ist und falls ja, das Herunterladen unterdrücken bzw. einen Fehler anzeigen.

**Comment by faqnet** [comment]
Bei den Stepprogrammen mach ich es so das ich den Add button disable nach einer 40xx Zeichen. 

Bei den Block könnte man es so machen das man nach jedem Eintrag einmal Flatted im Reducer und wenn die Länge vom Flat Output grösser ist als 40xx dann könnte man den neuen/veränderten EIntrag weg werfen und ein Alert werfen.

**Comment by dgruntz** [comment]
Eigentlich genügt es, wenn der `Upload` button deaktiviert wird wenn das Programm zu lange wird. Von mir aus kann man beliebig lange Programme definieren (d.h. der Add-Button könnte aktiv bleiben), aber man darf die langen Programme einfach nicht an den Roboter schicken, dieser Ansatz fünktioniert sowohl für Stepprogramme als auch für Blockprogramme. Ich weiss es nciht  mehr aber ich nehme an dass wir auf Blockprogrammen eine `length` methode definiert haben. Wenn nicht, dann ist diese schnell geschrieben.

Anstelle des disablen des buttons (das versteht man dann nicht) könnte man auch einfach einen Toast werfen mit der Meldung, dass das Programm zu lange ist. Diesen Test könnte man in der entsprechenden Methode einbauen der das Programm für den  upload übergeben wird.

**Comment by dgruntz** [comment]
Korrektur der Angabe oben: Es sind maximal 4096 Programmzeilen.

**Comment by dgruntz** [comment]
Ich denke, das wäre eine sinnvolle Ergänzung, d.h. vor einem Upload würde ich die Grösse testen, und wenn das Programm mehr als 4096 Programmzeilen hat, dann würde ich eine Meldung ausgeben.

Analog wenn das Programm leer ist (https://github.com/explore-it-org/robby-app/issues/282).
