### ISSUE TITLE
Batteriestand

### ISSUE THREAD

**Issue by JonasDev99** [explore-it-org/robby-app#225]
Wenn der Batteriestand zu niedrig ist, scheint der Roboter noch zu funktionieren und funktioniert auch ab und zu noch. Das Verhalten ist dann jedoch eher zufällig. Upload und Download kann dann manchmal festhängen oder sehr lange dauern. 

Dies sollte auf jeden Fall in der Anleitung unter Troubleshooting vermerkt sein.

Darum wäre es vielleicht nicht schlecht wenn man den Stand des Akkus wüsste und den Nutzer frühzeitig warnt, bevor dieser zu niedrig ist.

**Comment by dgruntz** [comment]
@2244stepe, kannst Du auf der Platine den Batteriestand abfragen?
Falls ja, dann könnten wir das Protokoll erweitern um diesen abfragen zu können, und wir können ihn in der App (z.B. unter Settings) darstellen.

**Comment by dgruntz** [comment]
Antwort von @2244stepe:

> Ja leider ist dafür ein weitere AD-Wandler Kanal notwendig, wenn ich
> es ganz «sauber» machen will. Eine denkbare Alternative dazu wäre,
> nur zu warnen, falls die «motoren»-Spannung zu tief liegt.
> Weil aber beide Teile (MCU und Motor) an derselben Speisung hängen,
> und in der MCU die «Referenzspannung zum AD-Converter» ebenfalls,
> kann man so gar nichts sehen, es skaliert sich einfach alles ratiometrisch
> nach unten, bis zu einer Spannung, wo die MCU nicht mehr läuft, auch wenn
> sie noch 100% rapportieren würde. He ja 2.5V von 2.5V sind auch 100%,
> aber eben zu wenig in Absolut.
> => Hardwarerevision abwarten

**Comment by dgruntz** [comment]
Mit der aktuellen Version der Platine kann dies nicht realisiert werden, daher schlage ich vor dass wir das vorerst schliessen.
Wir können dieses Issue wieder öffnen wenn die Platine diese Funktion unterstützt.
