### ISSUE TITLE
Duration Constraint

### ISSUE THREAD

**Issue by dgruntz** [explore-it-org/robby-app#235]
Im Feld "Duration" (auf der Seite Settings) sollte der Wert 0 nicht eingegeben werden können:

![image](https://user-images.githubusercontent.com/1516800/73405265-c488b080-42f3-11ea-9b65-9217ad80147a.png)

Ich vermute, der Code ist von den Motorenwerte-Eingabefeldern kopiert worden, denn dort ist 0 als unterer Wert erlaubt, aber bei Duration macht dies keinen Sinn.

**Comment by JonasDev99** [comment]
auf iOS kann 0 nicht eingegeben werden...

**Comment by JonasDev99** [comment]
Habe es so eben noch auf Android getestet und hier kann man 0 Eingeben
