### ISSUE TITLE
Version Check

### ISSUE THREAD

**Issue by dgruntz** [explore-it-org/robby-app#259]
Neu sollen die Versionen geprüft werden, d.h. wenn man versucht sich mit einem Roboter zu verbinden der nicht unterstützt wird, dann soll eine Meldung angezeigt werden. Eigentlich kann man danach die Verbindung gleich wieder trennen.

Und Version V006 ist eine Version die wir nicht unterstützen (da sie einen Fehler enthält). 

Bei der Meldung die angezeit wird könnten wir den Text unterscheiden, je nach dem welche Version der Roboter meldet.

Falls die Version vom Roboter grösser ist als die neueste von der App unterstützte Version, dann ist die App offenbar veraltet und man könnte dem Nutzer melden, dass er doch prüfen soll, ob im App-Store eine neue Version verfügbar ist.

Falls die Version vom Roboter kleiner ist als die neueste von der App unterstütze Version, dann versucht sich die App mit einem Roboter zu verbinden, dessen Version wir nicht unterstützen. Die meldung könnte den Nutzer darauf hinweisen, sich mit explore-it in Verbindung zu setzen.

**Comment by dgruntz** [comment]
Peter hat bestätigt dass aus seiner Sicht die Versioen

- VER 006
- VER 007
- VER 008

nicht unterstützt werden sollten.

**Comment by JonasDev99** [comment]
TODO: Texte in den Resourcefiles anpassen und übersetzen: 
unter Programming
- unsupportedAppVersionTitle
- unsupportedAppVersionMessage
- unsupportedRobotVersionTitle
- unsupportedRobotVersionMessage
- dialogCancelButton
