### ISSUE TITLE
Meldung Erfolg / Success

### ISSUE THREAD

**Issue by dgruntz** [explore-it-org/robby-app#266]
Wenn eine Datei gespeichert wird dann erscheint der Toast `Erfolg` oder `Success`. 

![image](https://user-images.githubusercontent.com/1516800/75340476-d9c11280-5892-11ea-8e45-521eb6e52ec7.png)

Diese Meldung sollte durch eine etwas aussagekräftigere Meldung ersetzt werden.

**Comment by dgruntz** [comment]
@JonasDev99 erzeuge doch eine (Word)-Datei in welcher erklärt wird, wo welche Meldungen aus dem Ressource-File verwendet wird, damit die Texte angepasst werden können.

**Comment by JonasDev99** [comment]
Da diese Meldung an mehreren / unterschiedlichen Orten verwendet wird passt sie sowieso nicht und kann nicht genauer definiert werden. Ich werde im Resourcenfile neue individuelle Meldungen anlegen.

**Comment by dgruntz** [comment]
OK.
Kannst Du diese Datei dann Daniel weiterleiten, damit er die Übersetzung machen lassen kann.
Und vielleicht kannst Du das Resourcefile in eine Word-Datei kopieren (damit wir keine Encoding Probleme haben) und dort gerade Kommentare eingügen, wann dieser Text verwendet wird.
