### ISSUE TITLE
VER 009: Upload / Download

### ISSUE THREAD

**Issue by dgruntz** [explore-it-org/robby-app#267]
Ich arbeite mit Roboter `6E:A5` und ich habe ein einfaches Programm mit 6 Zeilen definiert:

     1     2
     3     4
     5     6
     7     8
     9    10
    11    12

Wenn ich dieses Programm auf den Rechner hochlade dann werden die up- und download-Buttons deaktiviert, aber der upload terminiert nicht. Wenn ich auf "STOP" drücke, dann erscheint der Toast "Anweisungen erfolgreich auf den Roboter geladen", d.h. es hat zwei Probleme:

1) Der Upload funktioniert nicht
2) Die Meldung die kommt wenn ich den Prozess abbreche ist verwirrend.

Wenn ich versuche as Programm vom Roboter runterzuladen, dann terminiert dies ebenfalls nicht!
Und wenn ich "STOP" drücke, dann kommt auch die Meldung "Anweisungen erfolgreich vom Roboter runtergeladen" obwohl dies nicht der Fall ist. Zudem habe ich in diesem Fall ein Programm der Länge 0, d.h. KEINE Programmzeilen, und so ein Programm kann ich dann auch Speichern, das sollte nicht möglich sein, d.h. ich erwarte Probleme wenn ich ein Programm der Länge 0 auf den Roboter lade.

Ich weiss nicht ob dieses Problem beim Roboter oder bei der App liegt.

**Comment by dgruntz** [comment]
Das Problem tritt auch beim Rechner `AD:CF` auf.

**Comment by dgruntz** [comment]
Ich habe das auch noch mit dem Kay-Terminal angeschaut:

![image](https://user-images.githubusercontent.com/1516800/75357813-44ce1180-58b2-11ea-8f6f-3fec69b1f30c.png)


Ich gebe folgende Daten ein:
5A (Z) => VER 009
64 3F (d?) => d=000BFLSH
und dann ein Beam (B)
und als Antwort erhalte ich 
00 0B (die Länge)
00 (die erste Sequenznummer)
und dann die Daten. 

ABER: Wieso zeigt mir das Kay-Tool an dass das in mehreren Meldungen ausgeliefert wird? Warum kommt nach dem 0A ein Zeilenumbruch?

Könnte sein, dass dieses Zeichen als LF interpretiert wird, und kann sein, dass unser Programm unter demselben Problem leidet!
Und 0D ist ein CR.

**Comment by 2244stepe** [comment]
> Warum kommt nach dem 0A ein Zeilenumbruch?
> Könnte sein, dass dieses Zeichen als LF interpretiert
JA!
Kai's App hat Einstellungen für:
- Terminal (Display mode)
- Receive (newline behaviour)
- Send
- Misc.
Damit beim Empfang kein Zeilenumbruch "als empfangen" gilt, muss in den Einstellungen bei Receive <none> eingestellt sein. Dann ist das alles wie gewohnt. Diese beiden Zeichen 0x0D und 0x 0A kommen halt zufällig nur selten vor in den übertragenen Daten, darum sind wir nicht früher auf dieses Verhalten aufmerksam geworden.
Wie das in der App (BT-Stack) verarbeitet wird, ist mir unklar, aber ich nehme jetzt einmal an, das kommt nur als Zeichenkette ohne "Textfunktion" wie in einem Terminal.
> kann sein, dass unser Programm unter demselben Problem leidet!
Ich glaube nicht, sondern da ist ein anderes Problem noch im Busch. Untersuche gerade ...

**Comment by dgruntz** [comment]
Was muss bei Receive -> Newline eingestellt sein? Ich habe folgende optionen:

- CR+LF
- CR
- LF
- STX/ETX
- NUL
- None

und aktuell ist CR+LF eingestellt.

**Comment by 2244stepe** [comment]
<none> half bei  mir perfekt!
Alle anderen Optionen machen wieder etwas, was wir nicht wollen.

**Comment by 2244stepe** [comment]
Das ursprüngliche Beispiel mit 6 Zeilen (12 Werten) also d000B funktioniert hier am Terminal einwandfrei! Mir fällt nur folgendes auf: bei der Übertragung zum Robby musste bisher immer ein weiteres zusätzliches Zeichen gesandt werden (so habe ich das in der Beschreibung festgehalten). Hier ist das nun nicht mehr ein Zeichen mehr (zusätzlich), sondern ein weiteres Telegram, das nötig ist. Egal was, einfach etwas muss nachfolgen, damit meine State-Machine wieder am richtigen Ort ist. Könnte das in der App fehlen? Ich habe testweise auf VER 004 zurückgestellt, auch dort ist es so,
nach der korrekten Anzahl Werte übertragen genügt ein einzeln gesandtes "U" um den korrekten Response zu erhalten "FULL".
Natürlich wäre es besser, der Zähler auf dem Robby macht es richtig... ich schaue einmal, warum das so gemacht wurde und wie es besser sein könnte.

**Comment by 2244stepe** [comment]
Ich habe in einer VER 010 erfolgreich versucht, das zu korrigieren. Nun springt das script korrekt aus dem aktuellen State, wenn die korrekte Anzahl samples eingetroffen ist und meldet das auch sofort in Richtung App mit einem Response, ohne dass ein weiteres Zeichen folgen muss. 

=> Vorsicht: Dies wäre eine Änderung des Protokolls, wenn dies so belassen würde. Es entspricht aber viel besser dem, was man erwarten würde. 
 
==> Nun ist auch ein anderes Problem klar geworden: Wenn aus welchen Grund auch immer die App bei diesem "E" Command (Datentransfer APP->ROBBY) mehr Zeichen als benötigt sendet, werden aus den überschüssigen Zeichen vom Robby anschliessend Befehle ausgeführt, wenn in den Daten solche Zeichen erscheinen, die er als Befehle kennt. Dies bleibt ein grundsätzliches Problem, solange das Protokoll so primitiv ist, und kann zu unerwünschten Änderungen führen, die zufällig wirken, weil die Daten nicht jedesmal gleich sein werden.
Somit kommt dem "d" Kommando besondere Bedeutung zu: falls dies einmal nicht korrekt ankommt beim Robby, wird er anders zählen als die App und die oben beschriebene Situation tritt ein.

**Comment by dgruntz** [comment]
> Mir fällt nur folgendes auf: bei der Übertragung zum Robby musste bisher immer ein weiteres zusätzliches Zeichen gesandt werden (so habe ich das in der Beschreibung festgehalten). Hier ist das nun nicht mehr ein Zeichen mehr (zusätzlich), sondern ein weiteres Telegram, das nötig ist. Egal was, einfach etwas muss nachfolgen, damit meine State-Machine wieder am richtigen Ort ist. Könnte das in der App fehlen? 

Wir schicken in VER009 folgende Meldungen:
- `F`
- `dXXXX`
- `E`
- ein langes Byte-Array
- `end`

d.h. das letzte Zeichen wird als eigenes Telegramm geschickt.

> Ich habe testweise auf VER 004 zurückgestellt, auch dort ist es so,
nach der korrekten Anzahl Werte übertragen genügt ein einzeln gesandtes "U" um den korrekten Response zu erhalten "FULL".

Wir schicken in VER003 (auch auch bei VER004 ) folgende Meldungen:
- `F`
- `Dnn`
- `E`
- nn Telegramme der Form `NNN,NNNxx`
- `end`

> Natürlich wäre es besser, der Zähler auf dem Robby macht es richtig... ich schaue einmal, warum das so gemacht wurde und wie es besser sein könnte.

Das wäre dann aber eine neue Version! 

Ich habe bei uns im Code zwei Stellen gefunden die verdächtig aussehen, d.h. ich habe den Verdacht dass wir (bei VER009) nach einem Download auf unserer Seite nicht mehr aus diesem Zustand rauskommen.

**Comment by dgruntz** [comment]
> Ich habe in einer VER 010 erfolgreich versucht, das zu korrigieren. Nun springt das script korrekt aus dem aktuellen State, wenn die korrekte Anzahl samples eingetroffen ist und meldet das auch sofort in Richtung App mit einem Response, ohne dass ein weiteres Zeichen folgen muss.
> 
> => Vorsicht: Dies wäre eine Änderung des Protokolls, wenn dies so belassen würde. Es entspricht aber viel besser dem, was man erwarten würde.

OK, das wäre dann eine neue Protokollversion. Mit gefällt das ebenfalls besser als die aktuelle Version wo einfach "irgendwas" geschickt werden muss.

Wir werden uns aber vorerst um die Fehler in VER 009 kümmern.

 
> ==> Nun ist auch ein anderes Problem klar geworden: Wenn aus welchen Grund auch immer die App bei diesem "E" Command (Datentransfer APP->ROBBY) mehr Zeichen als benötigt sendet, werden aus den überschüssigen Zeichen vom Robby anschliessend Befehle ausgeführt, wenn in den Daten solche Zeichen erscheinen, die er als Befehle kennt. Dies bleibt ein grundsätzliches Problem, solange das Protokoll so primitiv ist, und kann zu unerwünschten Änderungen führen, die zufällig wirken, weil die Daten nicht jedesmal gleich sein werden.
> Somit kommt dem "d" Kommando besondere Bedeutung zu: falls dies einmal nicht korrekt ankommt beim Robby, wird er anders zählen als die App und die oben beschriebene Situation tritt ein.

Wir schicken sowohl bei VER003/4 als auch bei VER009 keine zusätzlichen Zeichen. Bei VER003/4 schicken wir 9 Bytes pro Zeile und dann das Token `end`, und bei VER009 schicken wir ein Byte-Array mit allen Daten und danach das Token `end`.

Aber das von Dir erwähnte Problem kann nicht gelöst werden, d.h. wenn wir mehr Zeilen schicken würden als das Programm erwartet (als mit `d` oder `D` angekündet worden ist) dann werden die weiteren Zeilen natürlich wieder als weitere Kommandos interpretiert.
