### ISSUE TITLE
AutoScroll

### ISSUE THREAD

**Issue by dgruntz** [explore-it-org/robby-app#278]
Wenn ein Programm geladen wird (z.B. beim Start der App oder vom Explorer-Tab) dann wird beim Einfügen der Zeilen jeweils an das Ende gescrollt. Das ist aber beim Öffnen eines Programms nicht nötig. Wenn man ein Word-Dokument aufmacht will man ja auch nicht das Ende sehen, sondern den Anfang.

Es macht jedoch weiterhin Sinn, dass wenn man mit dem `+`-Action Button eine Zeile einfügt, dass dann die neu eingefügte Zeile angezeigt wird, d.h. dass dann an das Ende des Programms gesprungen wird. Beim Laden sollte dieses Auto-Scroll jedoch deaktiviert werden.

**Comment by JonasDev99** [comment]
Notiz für mich: https://stackoverflow.com/questions/48863687/how-can-i-scroll-bottom-on-onpress-of-button-in-react-native

**Comment by JonasDev99** [comment]
Wenn ein ListItem ausgewählt ist, wird ja ein neues Item unten am ausgewählten eingefügt. Sollte dann auch dort hin gescrollt werden? Und ist dann immer noch das alte ListItem selektiert oder sollte das neue selektiert werden?

**Comment by dgruntz** [comment]
Wenn ich das richtig sehe ist dieses Issue _halb_ gelöst, d.h. beim Öffnen wird nicht mehr ans Ende gesprungen, aber wenn eine neue Zeile eingefügt wird, dann wird nicht an die Einfügestelle gesprungen.

**Comment by JonasDev99** [comment]
Ja, da muss ich nochmals dahinter... Ich glaube wir haben gesagt, dass bei einer gewissen Länge bis ans Ende gescrollt werden sollte, aber wenn es zu lang ist nicht mehr.

**Comment by JonasDev99** [comment]
Fixed in upcoming release
