### ISSUE TITLE
Check MTU

### ISSUE THREAD

**Issue by dgruntz** [explore-it-org/robby-app#280]
In der Docu zu react-ative-ble-plx habe ich folgende Methode [`requestMTUForDevice`](https://polidea.github.io/react-native-ble-plx/#blemanagerrequestmtufordevice) gefunden. Bitte checken was diese Methode auf unseren Android-Geräten zurückliefert.

Vielleicht helfen auch folgende Links/Methoden/Attribute weiter:

- [`Device.mtu`](https://polidea.github.io/react-native-ble-plx/#devicemtu)
- [`Device.requestMtu`](https://polidea.github.io/react-native-ble-plx/#devicerequestmtu)

**Comment by JonasDev99** [comment]
MTU ist die Grösse eines einzelnen Päckchens auf unterster Ebene. Das heisst, unsere 600 bytes sind in Wirklichkeit ca. 26 Päckchen a 23 bytes (default MTU Wert).

**Comment by dgruntz** [comment]
d.h. man kann nicht abfragen wieviele Bytes man verschicken kann?
Und ist das Resultat das bei dieser Methode (`Device.mtu`) auf Android und iOS dasselbe?

**Comment by JonasDev99** [comment]
Nein, jedenfalls nich über den mtu wert.
Ja auf iOS und Android ist dieser 23.

**Comment by dgruntz** [comment]
OK, dann hat sich das erledigt.
