### ISSUE TITLE
Probleme mit alten iPhones

### ISSUE THREAD

**Issue by dgruntz** [explore-it-org/robby-app#284]
> > Gestern habe ich via TestFlight die neueste Version (2.1.0 [21]) der Explore-it App Robotics geladen.
> > Leider kann ich diese Version auf meinem iPhone nicht öffnen. Es erscheint kurz der Titel Robotics und dann verschwindet alles (die App stürzt ab?) – oder ist sie ev. noch nicht für mich freigegeben?
Kannst du mir da weiterhelfen?
> 
> Lieber Dominik
> 
> Nein, leider funktioniert es auch mit der Version 2.1.1 nicht. Die App stürzt nach wie vor ab.
> 
> Herzlichen Gruss
> Rolf Hergert
> rolf.hergert@fhnw.ch

was ist der Stand mit dem iPhone von Rolf?

**Comment by JonasDev99** [comment]
Da war ich vor der IPA dran. Muss eine VM einrichten, damit ich alte iPhone Versionen testen kann.

**Comment by dgruntz** [comment]
Gibt es News zu diesem Issue/Problem?

**Comment by JonasDev99** [comment]
Leider nein, ich kann an dem Problem zurzeit nicht arbeiten, da ich kein Zugriff auf die VM habe um ein IPhone 5(s) zu simulieren. Sobald ich wieder Zugriff habe, werde ich daran weiter arbeiten. Evtl. könnte das Problem aber auch mit dem Updaten von React-Native weggehen...

Jedenfalls die minimale iOS Version ist 10.0, Android SDK 16.

**Comment by JonasDev99** [comment]
Konnte nun eine VM lokal installieren und das ganze auf einem iPhone 5s testen. Das Problem tritt bei mir im Emulator nicht mehr auf.

**Comment by JonasDev99** [comment]
@dgruntz ich habe so eben das Mail von Rolf nochmals gelesen und er hat ein iPhone 4s mit iOS 9. iOS 9 wird jedoch offiziell von React Native und sogar von Apple selbst nicht mehr unterstützt.
