### ISSUE TITLE
App-Store

### ISSUE THREAD

**Issue by dgruntz** [explore-it-org/robby-app#300]
In Issue #284 wurde festgehalten, dass die iOS App auf iOS 9 nicht mehr läuft:

> iOS 9 wird jedoch offiziell von React Native und sogar von Apple selbst nicht mehr unterstützt.

Ist es möglich dies auch im App-Store entsprechend einzugragen, d.h. dass es gar nicht mehr möglich ist, die App auf einem Gerät mit Version iOS 9 zu installieren? Jetzt kann sie installiert aber nicht gestartet werden, und das ist suboptimal.

**Comment by JonasDev99** [comment]
Habe ich in den Settings des Projektes angepasst

**Comment by dgruntz** [comment]
d.h. jetzt kann man es auf einem alten iOS nicht mehr installieren?

**Comment by JonasDev99** [comment]
Ja genau, mindestens iOS 10 wird nun verlangt
