### ISSUE TITLE
Programmabsturz bei langen Programmen (2)

### ISSUE THREAD

**Issue by dgruntz** [explore-it-org/robby-app#301]
Folgendes Szenario:

1) Settings => Intervall auf 50 setzen
2) Settings => Dauer auf 5 setzen
3) Programm aufzeichnen (Record)
4) Programm runterladen (=> Programm mit 250 Zeilen, dauert etwa 10Sek)
5) Scrollen an das Ende des Programms (da sind mehrere Wischbewegungen nötig) [1]
6) Einfügen einer neuen Programmzeile
7) Scrolling nach oben [2]

Das Programm ist mir einmal bereits an der Stelle [1] abgestürzt, aber immer an der Stelle [2].

Bugreports müssten auf dem  [Android-Portal](https://play.google.com/apps/publish/?account=5912664164285981355#AndroidMetricsErrorsPlace:p=org.exploreit.robotics&appid=4976362727805583574&appVersion=1576591854&showHidden=true&installSource=INSTALLED_FROM_ANYWHERE&clusterName=apps/org.exploreit.robotics/clusters/04b0b591&detailsAppVersion=1576591854&detailsSpan=7&detailsInstallSource=INSTALLED_FROM_ANYWHERE) sein.

**Comment by dgruntz** [comment]
Ist vielleicht dasselbe Problem das auch in https://github.com/explore-it-org/robby-app/issues/298 beschrieben ist. Jonas hat dort den Vermerk angefügt:

> Die Entwickler wissen Bescheid, der Issue wird hier getrackt: https://github.com/facebook/react-native/issues/17530

**Comment by JonasDev99** [comment]
Kann ich mit meinem iPhone auch nicht mit 1200 Zeilen reproduzieren.

**Comment by dgruntz** [comment]
Sehr gut wenn dieses Problem auf dem iPhone nicht auftritt!
Aber auf deinem Android kannst Du das reproduzieren, oder?
Sobald ich Version 2.2.2 habe werde ich das ausprobieren

**Comment by JonasDev99** [comment]
Ich habe es soeben auf Android 10 getestet und hier tritt der Fehler auch nicht mehr auf.
