### ISSUE TITLE
Programmlänge max 300

### ISSUE THREAD

**Issue by dgruntz** [explore-it-org/robby-app#302]
Ich habe folgende Programme erstellt:

- P0016 = Sequenzprogramm mit 16 Zeilen mit den Werten 1 bis 16
- P0032 = Blockprogramm mit 2 * P0016 = 32 Zeilen
- P0064 = Blockprogramm mit 2 * P0032 = 64 Zeilen
- P0128 = Blockprogramm mit 2 * P0064 = 128 Zeilen
- P0256 = Blockprogramm mit 2 * P0128 = 256 Zeilen
- P0512 = Blockprogramm mit 2 * P0256 = 512 Zeilen

P0016 kann ich ohne Probleme auf den Roboter laden und wieder zurück auf das Handy "beamen".

P0032 kann ich ohne Probleme auf den Roboter laden und wieder zurück auf das Handy "beamen".
Hochladen dauert (gefühlt) etwa 1 Sek.

P0064 kann ich ohne Probleme auf den Roboter laden und wieder zurück auf das Handy "beamen".
Hochladen dauert auch etwa 1 Sek

P0128 kann ich ohne Probleme auf den Roboter laden und wieder zurück auf das Handy "beamen".
Hochladen dauert auch etwa 2 Sek
Beim Runterladen ist die App abgestürzt, ich vermute beim Anzeigen des Programms, denn nach einem Neustart war das Programm geladen, d.h. Beamen hat funktioniert.

P0256 kann ich ohne Probleme auf den Roboter laden und wieder zurück auf das Handy "beamen".
Hochladen dauert auch etwa 4 Sek
Runterladen funktioniert.

P0512 kann ich nicht mehr auf den Roboter laden, d.h. ich habe diesen Download-Prozess 
jeweils nach 60Sek abgebrohen!
Wenn ich auf Stop klicke, dann meldet sich die App wieder (und meldet fälschlicherweise, dass die Instruktionen erfolgreich auf den Roboter geladen worden sind). Ich vermute, dass die App vom
Roboter keine Bestätigung erhalten hat dass das Programm angekommen ist (1024 Bytes).
Der Roboter scheint mir in einem sonderbaren Zustand zu sein, d.h. es hilft nur ein Reset des Roboters. Download funktioniert z.B. auch nicht mehr in dieser Situation.
Das Programm kann ich danach runterladen, aber die App stürzt ab (da Programm zu lang).
Nach einem Neustart der App kann ich das Programm anschauen, aber es sind nur etwas mehr als 18*16 Bytes übernommen worden, danach sind alles 100/100 gespeichert. Konkret sind 18*16 + 12=300 Zeilen geladen worden!
Das sind 600 Bytes. 

Mit der aktuellen Version kann man also maximal Programme mit 300 Zeilen laden.

Ich habe diese Zahlen noch verifiziert: Ein Programm der Länge 300 kann hochgeladen werden.
Ein Programm der Länge 301 kann nicht mehr hochgeladen werden.

Testgerät:
Pixel 2 / Android Version 10

**Comment by dgruntz** [comment]
Ich sehe zwei Lösungen:

1. Implementierung eines Chunked Uploads mit wie in https://github.com/explore-it-org/robby-app/issues/279 beschrieben Datenpaketen von maximal 512 Bytes (auch wenn bei meinem Test 600 Bytes auch noch gehen).
2. Beschränkung der Länge von Programmen auf 300, d.h. verbieten (vom Handy aus), dass Programme die Länger sind als 300 an den Roboter geladen werden können.

**Comment by JonasDev99** [comment]
Wurde mit #279 mittels Chunked Upload behoben
