### ISSUE TITLE
Roboter schickt "_end" nicht

### ISSUE THREAD

**Issue by JonasDev99** [explore-it-org/robby-app#307]
Wenn man 0 - 0 hochlädt und auf Abspielen drücket, kommt nie ein _end zurück - die App steckt im Abspielen-Zustand fest.

Kann auf Seite App abgefangen oder auf Seite Roboter behoben werden...

**Comment by dgruntz** [comment]
Ich kann dieses Verhalten bei mir nicht reproduzieren (ich habe v2.2.0 installiert).

Mit "Abspielen" meinst Du `G` (also [Go](https://github.com/explore-it-org/robby-app/blob/4e63404a5e5f7b192eaa599c4ef1cd9ab57c2fd0/src/ble/RobotProxy.js#L114)) und nicht `R`  (also [Run](https://github.com/explore-it-org/robby-app/blob/4e63404a5e5f7b192eaa599c4ef1cd9ab57c2fd0/src/ble/RobotProxy.js#L107))?
Ich frage, weil auf ein Run kein Resultat zurückkommt bis man Stop schickt.

Ich habe mit dem Kay-Terminal folgende Befehle an den Roboter geschickt (d.h. ich lade das Programm `0 - 0` hoch:

    F
    d0001
    E
    0x00 0x00
    G

und erhalte als Resultat zuerst ein `_GR_` und dann ein `_END`.

![image](https://user-images.githubusercontent.com/1516800/83568373-48151100-a523-11ea-943f-b454a6767955.png)

**Comment by JonasDev99** [comment]
Es lag daran, dass die Batterien meines Roboters leer waren.

**Comment by dgruntz** [comment]
Da hätte https://github.com/explore-it-org/robby-app/issues/225 geholfen.
