### ISSUE TITLE
Längenanzeige

### ISSUE THREAD

**Issue by dgruntz** [explore-it-org/robby-app#309]
Es wäre noch schön, wenn man (zumindest) bei einem Sequenzprogramm die Länge des Programms anzeigen könnte (z.B. gerade unterhalb des Textes "Speed from 0-100". Aber vielleicht vermisse ich diese Information auch nur jetzt beim Testen ;-)

**Comment by JonasDev99** [comment]
Habe dies nun bei beidem, jedoch bin ich mir nicht sicher, welche Länge bei einem Blockprogramm angezeigt werden sollte... Effektive länge (Instruktionen) oder anzahl Blöcke? Oder wie du oben geschrieben hast nur für Sequenzprogramme?

**Comment by dgruntz** [comment]
Ich hatte nur erwartet dass das bei Sequenzprogrammen angezeigt wird, aber wieso nicht auch bei Block-Programmen, dann aber die Anzahl Schritte (also in beiden Fällen dieselbe Information). Die Anzahl Blöcke ist nicht so hilfreich, denn das sieht man ja, aber die rekursive Struktur, das erkennt man nicht.
=> Ich würde also bei beiden (wenn möglcih) die Anzahl Instruktionen anzeigen.
