### ISSUE TITLE
Upload (v2.2.1)

### ISSUE THREAD

**Issue by dgruntz** [explore-it-org/robby-app#314]
Upload/Download funktioniert bei mir nicht mehr. Ich habe eben ein Sequenzprogramm mit 16 Zeilen geschrieben und hochgeladen, aber wenn ich dieses Programm wieder runterlade dann kommt nur der Spinner.

Ist dieses Problem allenfalls mit v2.2.2 behoben?

**Comment by JonasDev99** [comment]
Ja ist in Version 2.2.2 behoben.

**Comment by JonasDev99** [comment]
Ich glaube, das lag daran, dass nicht genug Daten hochgeladen wurden und der Roboter sich darum nachher im Upload Zustand befand...

**Comment by dgruntz** [comment]
OK, dann warte ich bis ich V2.2.2 auf meinem Rechner habe. Mit der Debug-Version funktioneirt es auf jeden Fall (habe ich eben ausprobiert).

**Comment by JonasDev99** [comment]
Debug-Version?

**Comment by dgruntz** [comment]
Ich meinte wenn ich nicht die Applikation aus dem Playstore starte sondern die App ab Konsole mit

    react-native run-android

starte. Und diese wird ja im Debug-Modus gestartet.

**Comment by JonasDev99** [comment]
Der Develop-Branch ist praktisch auf dem selben Stand wie Version 2.2.2

**Comment by dgruntz** [comment]
Ich bin auf dem master-branch. 
Letzter Commit:

```
Merge: 349af5a 66eb3d5
Author: Jonas Suter <jonas.suter@fhnw.ch>
Date:   Thu Jun 11 11:26:11 2020 +0200

    Merge pull request #313 from explore-it-org/develop

    Upload Fix

```

**Comment by JonasDev99** [comment]
stimmt, der ist auf dem Stand 2.2.2
