### ISSUE TITLE
App Name

### ISSUE THREAD

**Issue by dgruntz** [explore-it-org/robby-app#56]
ich habe gesehen dass an einigen Stellen im Konfigurationsfile ein „Programm Name“ hinterlegt ist, und zwar „Robotics“. Das ist nicht derselbe Name die der Paket-Identifier `org.exploreit.robotics`. Wenn ich das APK installieren will dann wird die folgende Meldung angezeigt: 

![image](https://user-images.githubusercontent.com/1516800/66931826-f2910000-f036-11e9-82b2-3982c42ea4b0.png)

Könnte man da anstelle von `Robotics` den Programmnamen `explore-it Robotics` verwenden, damit dann auch die Meldung kommt

    explore-it Robotics
    Du you want to install this application

?

**Comment by dgruntz** [comment]
Ich habe beim Reviewen gesehen dass dieser Name erscheint, und er unterscheidet sich vom Paketnamen. Habe mich gefragt, wo denn diser Name erscheint, und eine Stelle weiss ich jetzt.

Ich hätte gedacht, dass man dazu NUR diese Strings auswechseln muss (denn ansonsten scheint mir dieser String nicht kritisch zu sein), aber ich bin einverstanden wenn wir jetzt zuerst mal ein lauffähiges APK hinkrieben und uns erst später um diese Namenssache kümmern. 

Vielleicht genügt es die Methode

    protected String getMainComponentName() {
        return "Robotics";
    }

zu ändern. Im app.json ist neben einem Namen ein Display-Name aufgeführt:

    "name": "Robotics",
    "displayName": "Robotics"

vielleicht muss man auch diesen wechseln. Oder man könnte auch einfach alle "Robotics" durch "explore-it Robotics" ersetzen, dann sollte es eigentlich (....) immer noch funktionieren.

**Comment by dgruntz** [comment]
Wir müssen uns das wirklich nochmals überlegen (bzw. wissen, wo dieser Programmname überall verwendung findet). Die App heisst nach der Installation jetzt "Robotics" und das ist eigentlich ein guter Name. Ein Name wie explore-it Robotics scheint mir (als App-Name) zu lang zu sein.

**Comment by faqnet** [comment]
Der Name wird fast überall verwendet, problematisch ist der Namenswechsel weil je nachdem gewisse packages nicht gefunden werden/builds nicht mer funktionieren. Ein Namenswechsel ist wirklich eine sehr fragile Angelegenheit. Wenn wir das machen dann am besten wirklich nur in dem wir das Projekt neu erzeugen. Sonst wird es für uns fast unmöglich alles richtig aufzulösen.
