### ISSUE TITLE
Versionsnummer

### ISSUE THREAD

**Issue by dgruntz** [explore-it-org/robby-app#58]
Aktuell wird die Versionsnummer nicht angezeigt. Auf dem Settings-Dialog erscheint nur die Anzeige

![image](https://user-images.githubusercontent.com/1516800/67075267-1e24ff00-f18b-11e9-8108-e3b59e92ddf0.png)

Zudem sollten wir den auf diesem Schirm angezeigten Namen ändern von "robby app" auf "explore-it Robotics"

**Comment by dgruntz** [comment]
Die Versionsnummer ist in der Datei [App.js, Zeile 74](https://github.com/explore-it-org/robby-app/blob/master/App.js#L74) definiert. Den Namen der dort aufgeführt ist habe ich angepasst.

**Comment by faqnet** [comment]
Ich habe gerade ein Globales variablen File gemacht und dort Globale String definiere, push ich gleich
