### ISSUE TITLE
test android version (upgrade to RN 0.59) with more than 10 speed entries. Does it work?

### ISSUE THREAD

**Issue by jluthiger** [explore-it-org/robby-app#8]

**Comment by dgruntz** [comment]
Yes, I just defined a program with more than 10 speed entries (with [Build 17](https://appcenter.ms/users/explore-it.org/apps/robby-app-android/build/branches/master/builds/17)) and it works (actually it contains 15 statements).

**Comment by dgruntz** [comment]
Yes, I just defined a program with more than 10 speed entries (with [Build 17](https://appcenter.ms/users/explore-it.org/apps/robby-app-android/build/branches/master/builds/17)) and it works (actually it contains 15 statements).

**Comment by dgruntz** [comment]
Duplicate of #11 (or #11 adds a more precise description of the problem).
