### ISSUE TITLE
Programming View

### ISSUE THREAD

**Issue by dgruntz** [explore-it-org/robby-app#9]
If the programming view is opened then the last line is not completely shown but hidden behind the command bar. This is even worse if the cursor is inside this field.

It should be possible to scroll the program view up until the last line is above the action buttons, comparable to the situation when the view is edited.

![Screenshot_20190320-165019](https://user-images.githubusercontent.com/1516800/55973532-13425c80-5c86-11e9-96ff-eec171db9a5c.png)

**Comment by jluthiger** [comment]
Which version?

**Comment by dgruntz** [comment]
This was a "bug" reported by the customer, so it was a problem in Version 0.5.5 [Build 15](https://appcenter.ms/users/explore-it.org/apps/robby-app-android/build/branches/master/builds/15) which was distributed to the customer, but it is still an issue with the newest version [Build 17](https://appcenter.ms/users/explore-it.org/apps/robby-app-android/build/branches/master/builds/17).

**Comment by dgruntz** [comment]
Fixed with pull request #24.
